Repository livgust/covid-vaccine-scrapers, pull requests merged in 2021-03, with the labels that each got.

#98 Pediatrics of Greater Salem
  data/sites.json
  site-scrapers/PediatricAssociatesOfGreaterSalem.js
Labels: availability scraping

#111 Curative showing availability that isn't accessible to public yet
  site-scrapers/Curative/index.js
Labels: availability scraping

#105 Added timestamp and version to the data.json file.
  lib/s3.js
  main.js
Labels: architecture

#115 Show availability for Curative (again)
  site-scrapers/Curative/index.js
Labels: urgent

#94 Add Heywood Healthcare
  .github/workflows/nodejs.yaml
  .prettierignore
  data/sites.json
  package-lock.json
  site-scrapers/HeywoodHealthcare/config.js
  site-scrapers/HeywoodHealthcare/index.js
  test/Heywood/available-appointments.html
  test/Heywood/no-available-appointments.html
  test/HeywoodTest.js
  test/bootstrap.js
Labels: availability scraping

#143 URGENT: Color registration links corrected!
  site-scrapers/Color/config.js
Labels: urgent

#102 Add Baystate Health
  data/sites.json
  site-scrapers/BaystateHealth/config.js
  site-scrapers/BaystateHealth/index.js
  test/BaystateHealth.js
Labels: availability scraping

#160 MAImmunization: "more information" has blank line
  site-scrapers/MAImmunizations/index.js
Labels: bug

#161 Added "massVax" flag set to true for all Color & Curative sites.
  site-scrapers/Color/config.js
  site-scrapers/Color/index.js
  site-scrapers/Curative/config.js
  site-scrapers/Curative/index.js
Labels: UX enhancement

#194 finishing the rename of Workflow 1 in Workflow 2
  .github/workflows/prod_deploy.yaml
Labels: urgent
